-- RETIRED: legacy Neon Auth / per-row audit migration.
--
-- This file is intentionally non-executable.
--
-- Current production rules:
--   1. Neon Auth is not required for public reads.
--   2. silver.manage contains only: id, email, role.
--   3. silver.manage is a scope/permission list, not a content, timeline, governance, or audit table.
--   4. Per-row content audit triggers/functions are retired and must not be recreated.
--   5. silver.manage RLS must not be re-enabled by this legacy migration.
--   6. Scope time data lives in silver.<scope>_time.
--   7. Public SELECT permissions are maintained separately in public-anonymous-read.sql.
--
-- Historical SQL was removed to prevent accidental re-application of the
-- row-level audit/RLS design that caused write amplification and read failures.
