services:
  - type: web
    name: fortune-api
    env: python
    buildCommand: "cd fortune_api && pip install -r requirements.txt"
    startCommand: "cd fortune_api && python fortune_api.py"
    envVars:
      - key: FLASK_ENV
        value: production
