name = "moon-runes-pwa"
main = ".open-next/worker.js"
compatibility_date = "2026-09-22"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXTJS_ENV = "production"
