'use client';
import{useEffect,useMemo,useState}from'react';
import{createGame,currentRound,finalizeOpeningHand,normalizeRune,resolveEventRound,resonanceAction,finishResonanceRound,tiebreakAction,finishTiebreak}from'./game-engine';
import{actionDescriptor,applyPortableRuneAction}from'./action-engine';
import{MACRO_STATES}from'./game-data';import'./game.css';
const labels={perfect:'完美 +2',pass:'過關 +1',fair:'尚可 +0',fail:'不行 −1'};
export default function GameClient(){const[game,setGame]=useState(null),[selected,setSelected]=useState([[],[]]),[message,setMessage]=useState('載入月之符文…'),[actions,setActions]=useState(0),[inspect,setInspect]=useState(null);useEffect(()=>{fetch('/data/json/core/runes.json').then(r=>r.json()).then(rows=>{setGame(createGame(rows.map(normalizeRune)));setMessage('雙方先從 8 張起手牌各棄 3 張。');}).catch(()=>setMessage('無法載入符文資料。'));},[]);const round=useMemo(()=>game?currentRound(game):null,[game]);if(!game)return<main className="game-shell"><p>{message}</p></main>;
const toggle=(pi,id)=>setSelected(prev=>{const next=prev.map(x=>[...x]),list=next[pi];if(list.includes(id))next[pi]=list.filter(x=>x!==id);else if(list.length<(game.stage==='setup'?3:2))list.push(id);return next;});
const setup=()=>{try{setGame({...game,players:game.players.map((p,i)=>finalizeOpeningHand(p,selected[i])),stage:'play'});setSelected([[],[]]);setMessage('起手完成。R1 Event Phase。');}catch(e){setMessage(e.message);}};
const eventResolve=()=>{try{const next=resolveEventRound(game,selected),entry=next.log.at(-1);setGame(next);setSelected([[],[]]);setMessage(`A ${labels[entry.outcomes[0].result]}｜B ${labels[entry.outcomes[1].result]}`);}catch(e){setMessage(e.message);}};
const act=(kind)=>{try{const next=game.stage==='tiebreak'?tiebreakAction(game,game.activePlayer,kind):resonanceAction(game,game.activePlayer,kind);setGame(next);setActions(actions+1);setMessage(`${game.players[game.activePlayer].name}：${kind==='self'?'自我共振 +1':'破壞共振 −2'}`);}catch(e){setMessage(e.message);}};
const runeAct=(rune)=>{const d=actionDescriptor(rune);setInspect(d);if(d.migration!=='portable-prototype'){setMessage(`${rune.name}：保留歷史 Action prototype，等待雙卡 adapter；未套用猜測規則。`);return;}try{const next=applyPortableRuneAction(game,game.activePlayer,rune.id);setGame(next);setActions(actions+1);setMessage(`${rune.name}：${next.log.at(-1).note}`);}catch(e){setMessage(`${rune.name}：${e.message}`);}};
const finishRP=()=>{try{if(actions<2)throw new Error('雙方各需完成一次 Resonance action。');const next=game.stage==='tiebreak'?finishTiebreak(game):finishResonanceRound(game);setGame(next);setActions(0);setMessage(next.stage==='finished'?`${next.players[next.winner].name} 勝出。`:next.stage==='tiebreak'?'R8 尚未產生唯一結果，進入 R9 0′ RP。':'進入下一回合。');}catch(e){setMessage(e.message);}};
const event=game.eventDeck[game.eventIndex],isRP=game.stage==='tiebreak'||round?.type==='resonance'||round?.type==='final';return<main className="game-shell"><header><p className="eyebrow">LunaRunes × Game</p><h1>Semantic Playground</h1><p>Historical LOC2 → Current LunaRunes Game。</p><nav><a href="/lrunes/game/howto">玩法說明</a></nav></header><section className="status"><strong>{game.stage==='setup'?'起手設定':game.stage==='tiebreak'?"R9 · 0′ Resonance Phase":game.stage==='finished'?'遊戲結束':`R${round?.round} · ${round?.label}`}</strong><span>{message}</span></section>{game.stage==='play'&&round?.type==='event'&&<section className="event"><small>{event.id} · {event.group}</small><h2>{event.title}</h2><p>{event.description}</p><code>{event.signature}</code></section>}<section className="macro">{Object.entries(MACRO_STATES).map(([k,v])=><span key={k}><b>{k}</b> {v.zh}</span>)}</section>{inspect&&<section className="action-inspector"><strong>{String(inspect.runeId).padStart(2,'0')} {inspect.name}</strong><p>Current 角色行動：{inspect.canonAction||'—'}</p><p>Historical prototype：{inspect.legacyPrototype||'—'}</p><small>{inspect.migration==='needs-dual-card-adapter'?'需 Dual-card adapter，暫不自動執行。':'可移植 prototype；若需要 target/選牌，介面會等待後續控制器。'}</small></section>}<div className="players">{game.players.map((p,pi)=><section className="player" key={p.name}><h2>{p.name}</h2><p>De {p.de}/16 {p.star?'★':''}</p><div className="hand">{p.hand.map(c=><div className={selected[pi].includes(c.id)?'card-wrap selected-wrap':'card-wrap'} key={c.id}><button type="button" disabled={game.stage==='finished'} className={selected[pi].includes(c.id)?'card selected':'card'} onClick={()=>toggle(pi,c.id)}><small>{String(c.id).padStart(2,'0')} · {c.group} · {c.macro||'SYSTEM'}</small><strong>{c.name}</strong><span>{c.action}</span></button>{isRP&&game.activePlayer===pi&&game.stage!=='finished'&&<button type="button" className="skill" onClick={()=>runeAct(c)}>使用角色行動</button>}</div>)}</div></section>)}</div><footer>{game.stage==='setup'?<button className="primary" onClick={setup}>雙方棄 3 張，開始</button>:game.stage==='finished'?<button className="primary" onClick={()=>location.reload()}>重新開始</button>:isRP?<div><p>輪到：{game.players[game.activePlayer].name}</p><button className="primary" onClick={()=>act('self')}>自我共振 +1</button> <button className="primary" onClick={()=>act('attack')}>破壞共振 −2</button> <button className="primary" onClick={finishRP}>完成 RP</button></div>:<button className="primary" onClick={eventResolve}>雙卡結算 Event</button>}</footer></main>}
