import { EVENTS, GROUP_TO_MACRO, RESULT_DE, ROUND_PLAN } from './game-data';
export function shuffle(items){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
export function normalizeRune(raw){return{id:Number(raw['編號']),name:raw['符文名稱'],english:raw['英文'],group:raw['所屬分組'],macro:GROUP_TO_MACRO[raw['所屬分組']]||null,action:raw['角色行動']||''};}
export function createPlayer(name,runes){const deck=shuffle(runes.filter(r=>r.id>=1&&r.id<=66));return{name,de:0,star:false,starSince:null,deck,hand:deck.slice(0,8),discard:[],setupDiscardRemaining:3};}
export function finalizeOpeningHand(player,discardIds){if(discardIds.length!==3)throw new Error('起手必須從 8 張中棄 3 張。');const ids=new Set(discardIds);if(ids.size!==3||discardIds.some(id=>!player.hand.some(c=>c.id===id)))throw new Error('起手棄牌不合法。');const discarded=player.hand.filter(c=>ids.has(c.id));return{...player,hand:player.hand.filter(c=>!ids.has(c.id)),discard:[...player.discard,...discarded],deck:player.deck.slice(8),setupDiscardRemaining:0};}
export function refillToFive(player){const need=Math.max(0,5-player.hand.length);return{...player,hand:[...player.hand,...player.deck.slice(0,need)],deck:player.deck.slice(need)};}
export function applyDe(player,delta,round){const de=Math.max(0,Math.min(16,player.de+delta));const gained=de===16&&player.de<16;return{...player,de,star:de===16,starSince:gained?round:(de<16?null:player.starSince)};}
export function evaluateDualCard(cards,event){if(cards.length!==2)throw new Error('Current Game Event 回應固定為雙卡。');const played=cards.map(c=>c.macro).filter(Boolean),required=[...event.requirements];let hits=0;for(const macro of played){const i=required.indexOf(macro);if(i>=0){hits++;required.splice(i,1);}}const full=required.length===0&&hits===event.requirements.length;const result=full?'perfect':hits===2?'pass':hits===1?'fair':'fail';return{result,delta:RESULT_DE[result],hits,required:event.requirements.length,alphaAdapter:true};}
export function createGame(runes){return{stage:'setup',roundIndex:0,eventDeck:shuffle(EVENTS),eventIndex:0,players:[createPlayer('玩家 A',runes),createPlayer('玩家 B',runes)],log:[],winner:null,activePlayer:0,rpActions:0};}
export function currentRound(game){return ROUND_PLAN[game.roundIndex]||null;}
export function resolveEventRound(game,selections){const event=game.eventDeck[game.eventIndex],round=currentRound(game);const outcomes=game.players.map((p,i)=>{const cards=p.hand.filter(c=>selections[i].includes(c.id)),outcome=evaluateDualCard(cards,event);let next=applyDe(p,outcome.delta,round.round);next={...next,hand:next.hand.filter(c=>!selections[i].includes(c.id)),discard:[...next.discard,...cards]};return{player:refillToFive(next),outcome,cards};});return{...game,players:outcomes.map(x=>x.player),eventIndex:game.eventIndex+1,roundIndex:game.roundIndex+1,rpActions:0,log:[...game.log,{round:round.round,type:'event',event:event.id,outcomes:outcomes.map(x=>({result:x.outcome.result,delta:x.outcome.delta,cards:x.cards.map(c=>c.id)}))}]};}
function doResonance(game,playerIndex,kind,roundNumber,type){if(playerIndex!==game.activePlayer)throw new Error('尚未輪到此玩家。');const target=kind==='self'?playerIndex:1-playerIndex,delta=kind==='self'?1:-2;return{...game,players:game.players.map((p,i)=>i===target?applyDe(p,delta,roundNumber):p),activePlayer:1-playerIndex,rpActions:game.rpActions+1,log:[...game.log,{round:roundNumber,type,actor:playerIndex,action:kind,delta}]};}
export function resonanceAction(game,playerIndex,kind){return doResonance(game,playerIndex,kind,currentRound(game).round,'resonance');}
export function tiebreakAction(game,playerIndex,kind){return doResonance(game,playerIndex,kind,9,'0prime');}
export function finishResonanceRound(game){if(game.rpActions!==2)throw new Error('Resonance Phase 必須雙方各行動一次。');const round=currentRound(game),qualified=game.players.map((p,i)=>p.star&&p.starSince!==round.round?i:null).filter(i=>i!==null);if(qualified.length===1)return{...game,winner:qualified[0],stage:'finished'};if(round.type==='final')return{...game,stage:'tiebreak',roundIndex:8,activePlayer:0,rpActions:0};return{...game,roundIndex:game.roundIndex+1,activePlayer:0,rpActions:0};}
export function finishTiebreak(game){if(game.rpActions!==2)throw new Error("0′ RP 必須雙方各行動一次。");const qualified=game.players.map((p,i)=>p.star?i:null).filter(i=>i!==null);if(qualified.length===1)return{...game,winner:qualified[0],stage:'finished'};const max=Math.max(...game.players.map(p=>p.de)),leaders=game.players.map((p,i)=>p.de===max?i:null).filter(i=>i!==null);if(leaders.length===1)return{...game,winner:leaders[0],stage:'finished'};return{...game,activePlayer:0,rpActions:0};}
