import{EVENTS,GROUP_TO_MACRO,RESULT_DE,ROUND_PLAN,ALPHA_HAND_RULE}from'./game-data';
export function shuffle(items){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
export function normalizeRune(raw){return{id:Number(raw.id??raw['編號']),name:raw.name??raw['符文名稱'],english:raw.english??raw['英文'],group:raw.group??raw['所屬分組'],macro:raw.macro??GROUP_TO_MACRO[raw.group??raw['所屬分組']]||null,action:raw.action??raw['角色行動']??''};}
export function createPlayer(name,runes){const deck=shuffle(runes.filter(r=>r.id>=1&&r.id<=66));return{name,de:0,star:false,starSince:null,deck,hand:deck.slice(0,8),discard:[],setupDiscardRemaining:3};}
export function createPlayers(count,runes){return Array.from({length:count},(_,i)=>createPlayer(`玩家 ${String.fromCharCode(65+i)}`,runes));}
export function finalizeOpeningHand(player,discardIds){if(discardIds.length!==3)throw new Error('起手必須從 8 張中棄 3 張。');const ids=new Set(discardIds);if(ids.size!==3||discardIds.some(id=>!player.hand.some(c=>c.id===id)))throw new Error('起手棄牌不合法。');const discarded=player.hand.filter(c=>ids.has(c.id));return{...player,hand:player.hand.filter(c=>!ids.has(c.id)),discard:[...player.discard,...discarded],deck:player.deck.slice(8),setupDiscardRemaining:0};}
export function drawCards(player,count){const room=Math.max(0,ALPHA_HAND_RULE.tempCap-player.hand.length),n=Math.min(count,room,player.deck.length);return{...player,hand:[...player.hand,...player.deck.slice(0,n)],deck:player.deck.slice(n)};}
export function refillToFive(player){return drawCards(player,Math.max(0,ALPHA_HAND_RULE.base-player.hand.length));}
export function discardOverflow(player,discardIds=[]){const excess=Math.max(0,player.hand.length-ALPHA_HAND_RULE.keepLimit);if(!excess)return player;if(discardIds.length!==excess)throw new Error(`效果結算後手牌超過 5，請棄 ${excess} 張。`);const ids=new Set(discardIds);if(ids.size!==excess||discardIds.some(id=>!player.hand.some(c=>c.id===id)))throw new Error('Overflow 棄牌不合法。');const cards=player.hand.filter(c=>ids.has(c.id));return{...player,hand:player.hand.filter(c=>!ids.has(c.id)),discard:[...player.discard,...cards]};}
export function applyDe(player,delta,round){const de=Math.max(0,Math.min(8,player.de+delta));return{...player,de,star:false,starSince:null};}
// Alpha coverage adapter: two played runes each contribute their macro plus their concrete group slot.
// This restores the historical 4/4..0/4 result ladder without changing the fixed two-card Event response.
export function evaluateDualCard(cards,event){if(cards.length!==2)throw new Error('Current Game Event 回應固定為雙卡。');const required=event.requirements;let macroHits=0;const pool=[...required];for(const c of cards){const i=pool.indexOf(c.macro);if(i>=0){macroHits++;pool.splice(i,1);}}const groupDiversity=new Set(cards.map(c=>c.group)).size;const coverage=Math.min(4,macroHits+Math.min(2,groupDiversity));const result=coverage===4?'perfect':coverage===3?'pass':coverage===2?'fair':coverage===1?'replenish':'fail';return{result,delta:RESULT_DE[result],coverage,required:required.length,alphaAdapter:true};}
export function createGame(runes,playerCount=2){if(![2,3,4].includes(playerCount))throw new Error('Alpha 目前支援 2–4 人。');return{stage:'setup',mode:playerCount===2?'duel':'multiplayer',playerCount,roundIndex:0,eventDeck:shuffle(EVENTS),eventIndex:0,players:createPlayers(playerCount,runes),log:[],winner:null,activePlayer:0,rpActions:0};}
export function multiplayerRoundPlan(){return Array.from({length:8},(_,i)=>({round:i+1,type:i%2===0?'event':(i===7?'final-battle':'battle'),label:i%2===0?'Cooperative Event':'Battle'}));}
export function currentRoundFor(game){return game.mode==='multiplayer'?multiplayerRoundPlan()[game.roundIndex]||null:currentRound(game);}
export function currentRound(game){return ROUND_PLAN[game.roundIndex]||null;}
export function resolveEventRound(game,selections){const event=game.eventDeck[game.eventIndex],round=currentRoundFor(game);const outcomes=game.players.map((p,i)=>{const cards=p.hand.filter(c=>selections[i].includes(c.id)),outcome=evaluateDualCard(cards,event);let next=applyDe(p,outcome.delta,round.round);next={...next,hand:next.hand.filter(c=>!selections[i].includes(c.id)),discard:[...next.discard,...cards]};const draw=outcome.result==='fail'?ALPHA_HAND_RULE.failDraw:ALPHA_HAND_RULE.eventDraw;next=drawCards(next,draw);return{player:next,outcome,cards,draw};});return{...game,players:outcomes.map(x=>x.player),eventIndex:game.eventIndex+1,roundIndex:game.roundIndex+1,rpActions:0,log:[...game.log,{round:round.round,type:'event',event:event.id,outcomes:outcomes.map(x=>({result:x.outcome.result,delta:x.outcome.delta,coverage:x.outcome.coverage,draw:x.draw,cards:x.cards.map(c=>c.id)}))}]};}
function doResonance(game,playerIndex,kind,roundNumber,type){if(playerIndex!==game.activePlayer)throw new Error('尚未輪到此玩家。');if(game.rpActions>=2)throw new Error('本次 Resonance Phase 已完成雙方行動。');const target=kind==='self'?playerIndex:1-playerIndex,delta=kind==='self'?1:-2;return{...game,players:game.players.map((p,i)=>i===target?applyDe(p,delta,roundNumber):p),activePlayer:1-playerIndex,rpActions:game.rpActions+1,log:[...game.log,{round:roundNumber,type,actor:playerIndex,action:kind,delta}]};}
export function resonanceAction(game,playerIndex,kind){return doResonance(game,playerIndex,kind,currentRoundFor(game).round,'resonance');}
export function battleAction(game,playerIndex,targetIndex,delta=-1){const round=currentRoundFor(game);if(game.mode!=='multiplayer'||!['battle','final-battle'].includes(round?.type))throw new Error('目前不是 Battle 回合。');if(playerIndex!==game.activePlayer)throw new Error('尚未輪到此玩家。');if(targetIndex===playerIndex||targetIndex<0||targetIndex>=game.players.length)throw new Error('Battle 必須指定其他玩家。');const strength=Math.max(1,Math.min(4,Math.abs(delta)));const players=game.players.map((p,i)=>i===targetIndex?applyDe(p,-strength,round.round):p);const actions=game.rpActions+1,next=actions>=game.players.length?0:(playerIndex+1)%game.players.length;return{...game,players,activePlayer:next,rpActions:actions,log:[...game.log,{round:round.round,type:'battle',actor:playerIndex,target:targetIndex,strength}]};}
export function finishBattleRound(game){const round=currentRoundFor(game);if(game.rpActions!==game.players.length)throw new Error('Battle 必須每位玩家各完成一次行動。');if(round.type==='final-battle'){const max=Math.max(...game.players.map(p=>p.de)),leaders=game.players.map((p,i)=>p.de===max?i:null).filter(i=>i!==null);return leaders.length===1?{...game,winner:leaders[0],stage:'finished'}:{...game,stage:'draw',winner:null};}return{...game,roundIndex:game.roundIndex+1,activePlayer:0,rpActions:0};}
export function duelAction(game,playerIndex,kind){return doResonance(game,playerIndex,kind,9,'final-duel');}
export function beginResonance(game){return{...game,players:game.players.map(refillToFive),activePlayer:0,rpActions:0};}
export function finishResonanceRound(game){if(game.rpActions!==2)throw new Error('Resonance Phase 必須雙方各行動一次。');const round=currentRoundFor(game);if(round.type==='final'){const max=Math.max(...game.players.map(p=>p.de)),leaders=game.players.map((p,i)=>p.de===max?i:null).filter(i=>i!==null);if(leaders.length===1)return{...game,winner:leaders[0],stage:'finished'};return{...game,stage:'duel',activePlayer:0,rpActions:0};}return{...game,roundIndex:game.roundIndex+1,activePlayer:0,rpActions:0};}
export function finishDuel(game){if(game.rpActions!==2)throw new Error('R9 Duel 必須雙方各完成一次對戰行動。');const [a,b]=game.players;if(a.de===b.de)throw new Error('R9 Duel 應直接決出高低；請檢查 Duel action 規則。');return{...game,winner:a.de>b.de?0:1,stage:'finished'};}
