'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { fetchLocJson, fetchLocJsonBatch, LOC_DATA } from '../loc/data';
import { evaluateSpread, finalGuidance, splitDomainGuidance } from '../loc/model/semantic-guidance';
import { allData as adviceData } from '../../js/rune_all_data_all.js';
import { buildRuneGraph, searchRuneGraph } from '../../js/rune-graph-core.js';
import RuneAtlas from './RuneAtlas';

const DIRECTIONS=['正位','半正位','半逆位','逆位'];
const ROTATION_CLASSES=['rune-rotate-0','rune-rotate-90','rune-rotate-n90','rune-rotate-180'];
const GROUP_ORDER=['靈魂','連結','生命','自然','礦物','元素','秩序','無序','特殊'];
const PAGE_SIZE=10;
const MODES=[
  {key:'single',count:1,label:'單卡',positions:['核心']},
  {key:'daily',count:1,label:'每日',positions:['今日']},
  {key:'2card',count:2,label:'雙卡',positions:['因','果']},
  {key:'3card',count:3,label:'三卡',positions:['源','轉','合']},
  {key:'5card',count:5,label:'五卡',positions:['過去','現在','未來','外在','內在']},
  {key:'ow3gs',count:11,label:'11卡 OW3gs',positions:['1','2','3','4','5','6','7','8','9','10','11']}
];
const RITUAL_MESSAGES={
  single:['您目前使用的是「單卡占卜模式」。','占卜中，請稍等片刻，馬上就好……','正在找尋那命運之線……','微弱的月光，會在漆黑的夜裡，帶領你找到方向。','抓到命運絲線的軌跡了，現在呈現。'],
  daily:['您目前使用的是「單卡每日抽牌模式」。','抽牌中，請稍等片刻，馬上就好……','這是一張屬於今日節奏與提醒的指引牌。','微弱的月光，會在漆黑的夜裡，帶領你找到方向。','今日月符已經抽取完成。'],
  '2card':['您目前使用的是「雙卡占卜模式」。','占卜中，請稍等片刻，馬上就好……','第一張卡牌為「因」，第二張卡牌為「果」。','正在整理兩張牌之間的前後關係。','抓到命運絲線的軌跡了，現在呈現。'],
  '3card':['您目前使用的是「三卡占卜模式」。','占卜中，請稍等片刻，馬上就好……','第一張為「源」，第二張為「轉」，第三張為「合」。','正在整理這次抽取的變化路徑。','抓到命運絲線的軌跡了，現在呈現。'],
  '5card':['您目前使用的是「五卡占卜模式」。','占卜中，請稍等片刻，馬上就好……','前三張依序觀看過去、現在與未來。','第四張看外在條件，第五張看內在狀態。','正在把時間主線與內外條件整合成完整解讀。'],
  ow3gs:['您目前使用的是「OW3gs 11卡模式」。','占卜中，請稍等片刻，馬上就好……','前六張建立整體脈絡。','第七至第十一張進入核心判定。','十一張命運絲線已經整理完成。']
};

function randomInt(max){if(max<=1)return 0;if(globalThis.crypto?.getRandomValues){const limit=Math.floor(0x100000000/max)*max;const value=new Uint32Array(1);do{crypto.getRandomValues(value)}while(value[0]>=limit);return value[0]%max;}return Math.floor(Math.random()*max);}
function sampleUnique(items,count){const pool=[...items];for(let i=pool.length-1;i>0;i--){const j=randomInt(i+1);[pool[i],pool[j]]=[pool[j],pool[i]];}return pool.slice(0,count);}
function runeCardImage(card){const number=String(Number(card?.編號)||0).padStart(2,'0');const name=String(card?.符文名稱||'').replace(/之符文$/,'').trim();return `/assets/lunarunes/cards/${number}_${name}.png`;}
function realMoonPhase(date=new Date()){try{const formatter=new Intl.DateTimeFormat('zh-TW-u-ca-chinese',{year:'numeric',month:'numeric',day:'numeric'});const day=Number(formatter.formatToParts(date).find(part=>part.type==='day')?.value);if(day<=7)return '新月';if(day<=14)return '上弦';if(day<=21)return '滿月';if(day<=28)return '下弦';if(day<=30)return '空亡';}catch{}return '未知';}
function initialMode(){if(typeof window==='undefined')return 'single';const value=new URLSearchParams(window.location.search).get('mode')||'single';return MODES.some(item=>item.key===value)?value:'single';}
function directionText(card,direction){const field=({'正位':'正向表示','半正位':'半正向表示','半逆位':'半逆向表示','逆位':'逆向表示'})[direction];return card?.[field]||'';}
function phaseAdvice(card,direction,phase){const row=adviceData.find(item=>item?.符文名稱===card?.符文名稱);return row?.卡牌方向?.find(item=>item?.方向===direction)?.現況?.find(item=>item?.現在月相===phase)||null;}
function narrativeCore(card,direction){return directionText(card,direction).replace(/[。！？]+$/g,'').trim().replace(/^我(?=與|在|正|開始|逐漸|感|看|聽|覺|願|能|會|已|仍|將|對|被|把|讓|從|以|失|逃|拒|壓|忽|迷|清|珍|擁|接|學|勇|專|持|面|承|順|相|回|找|守|展|放|斬|保|選|領|接納)/,'').replace(/我的/g,'自身的').replace(/我自己/g,'自身').replace(/自己/g,'自身').replace(/讓我/g,'讓自身').replace(/^正在/,'正處於');}
function derivedFromEvolution(history){return (history?.semantic_history_cases||[]).filter(item=>item?.title&&item.title!=='混沌三兄弟').map(item=>{const parts=String(item.title).split('→').map(value=>value.trim());const target=parts.length>1?parts.at(-1):'';const resolvedRune=/^[靈魂彩憶界域鏡核向斷封鍊啟分悟誤生老病死心愛語韻樹花葉草根種實枝金玉晶地石鑽礦塵光暗水火風土雷氣日月星辰明時空因福禍無夢幻緣虛果玄命]$/.test(target)?target:null;const relation=item.kind||'derived';return {term:parts[0]||item.title,relation,resolved_rune:resolvedRune,status:relation==='balanced_ambiguity'?'ambiguous':relation.includes('out_of_domain')?'special':'confirmed',note:item.note||''};});}

function SingleAdvice({card,direction,phase,daily=false}){const info=phaseAdvice(card,direction,phase);if(!info)return <p>目前沒有這組月相與位向的補充資料。</p>;if(daily)return <div className="runes-advice-grid"><article><strong>今日核心</strong><span>{info.每日占卜提醒||info.狀況表達}</span></article><article><strong>狀況</strong><span>{info.狀況形容}</span></article><article><strong>表達</strong><span>{info.狀況表達}</span></article><article><strong>引導</strong><span>{info.每日占卜引導}</span></article><article><strong>祝福</strong><span>{info.每日占卜祝福}</span></article></div>;return <><p className="runes-reading-lead"><strong>占卜結論｜{card.符文名稱}・{direction}</strong><span>{directionText(card,direction)}</span></p><div className="runes-advice-grid"><article><strong>愛情</strong><span>{info.愛情建議}</span></article><article><strong>事業</strong><span>{info.事業建議}</span></article><article><strong>心理</strong><span>{info.心理建議}</span></article><article><strong>健康</strong><span>{info.健康建議}</span></article><article><strong>生活</strong><span>{info.生活建議}</span></article></div></>}

function MultiReading({draw,mode,phase}){if(!draw)return null;const cards=draw.cards,directions=draw.directions;if(mode==='2card'||mode==='3card'){const labels=mode==='2card'?['因','果']:['源','轉','合'];return <section className="loc-card" data-draw-reading={mode}><p className="loc-eyebrow">Reading · 完整解讀</p><h2>{mode==='2card'?'因 → 果':'源 → 轉 → 合'}</h2><p><strong>完整現況：</strong>{cards.map((card,index)=>`${labels[index]}「${card.符文名稱}」${directions[index]}`).join('、')}。目前真實月相為{phase}。</p><p><strong>閱讀方式：</strong>{mode==='2card'?'先看造成現況的「因」，再看它導向的「果」。':'依序閱讀「源 → 轉 → 合」，先找起點，再看轉化，最後看收束。'}</p><div className="loc-context-list">{cards.map((card,index)=><div className="loc-context-item" key={`${mode}-${card.編號}-${index}`}><strong>{labels[index]}：{card.符文名稱}・{directions[index]}</strong><span>{directionText(card,directions[index])}</span></div>)}</div></section>}
  if(mode==='5card'){const [past,present,future,external,internal]=cards;const core=cards.map((card,index)=>narrativeCore(card,directions[index]));return <section className="loc-card" data-draw-reading="5card"><p className="loc-eyebrow">Reading · 五卡完整解讀</p><h2>時間主線 × 內外作用</h2><p><strong>時間主線：</strong>過去的「{past.符文名稱}」{directions[0]}指出，曾有「{core[0]}」的背景；到了現在，「{present.符文名稱}」{directions[1]}把重點帶到「{core[1]}」。若目前走勢延續，未來的「{future.符文名稱}」{directions[2]}則顯示局勢可能朝「{core[2]}」發展。</p><p><strong>內外作用：</strong>外在的「{external.符文名稱}」{directions[3]}顯示「{core[3]}」；內在的「{internal.符文名稱}」{directions[4]}則顯示「{core[4]}」。前者描述環境與他人的作用，後者描述自身如何承接與回應，因此兩者會共同改變前三張時間主線的實際走向。</p><p><strong>閱讀原則：</strong>先處理現在牌所指出的核心，再觀察外在與內在是否彼此拉扯或互相支持；未來牌視為延續目前條件後的趨勢，不作絕對斷定。本次真實月相為{phase}。</p><details className="reading-details"><summary>查看五張牌逐張解讀</summary><div className="loc-context-list">{cards.map((card,index)=><div className="loc-context-item" key={`five-${card.編號}-${index}`}><strong>{['過去','現在','未來','外在','內在'][index]}：{card.符文名稱}・{directions[index]}</strong><span>{directionText(card,directions[index])}</span></div>)}</div></details></section>}
  return null;
}

export default function RunesClient(){
  const [data,setData]=useState(null),[error,setError]=useState(''),[modeKey,setModeKey]=useState('single'),[draw,setDraw]=useState(null),[group,setGroup]=useState('全部'),[ritualStep,setRitualStep]=useState(-1),[graphQuery,setGraphQuery]=useState(''),[graphGroup,setGraphGroup]=useState(''),[graphEdge,setGraphEdge]=useState(''),[nodePage,setNodePage]=useState(1),[edgePage,setEdgePage]=useState(1);const timers=useRef([]);
  useEffect(()=>{
    setModeKey(initialMode());
    let live=true;
    fetchLocJson(LOC_DATA.RUNES).then(runes=>{
      if(!live)return;
      const canonicalRunes=(runes||[]).filter(row=>Number(row?.編號)>=1&&Number(row?.編號)<=66);
      if(!canonicalRunes.length)throw new Error('canonical runes.json 沒有可抽取符文。');
      setData({runes:canonicalRunes,lots:[],evolution:{},writing:{},relationships:{},eras:{}});
      setError('');
      fetchLocJson(LOC_DATA.LOTS).then(lots=>{if(live)setData(previous=>previous?{...previous,lots:lots||[]}:previous);}).catch(()=>{});
      fetchLocJsonBatch([LOC_DATA.LUNARUNE_EVOLUTION_HISTORY,LOC_DATA.LOC4_WRITING_REGISTRY,LOC_DATA.LOC_CROSS_RELATIONSHIP_REGISTRY,LOC_DATA.LOC_ERA_REGISTRY],{concurrency:2}).then(([evolution,writing,relationships,eras])=>{if(!live)return;setData(previous=>previous?{...previous,evolution:evolution||{},writing:writing||{},relationships:relationships||{},eras:eras||{}}:previous);}).catch(()=>{});
    }).catch(err=>live&&setError(`月之符文核心資料載入失敗：${err?.message||'未知錯誤'}`));
    return()=>{live=false;timers.current.forEach(clearTimeout);};
  },[]);
  const selectedMode=useMemo(()=>MODES.find(item=>item.key===modeKey)||MODES[0],[modeKey]);const groups=useMemo(()=>{const available=new Set((data?.runes||[]).map(row=>row.所屬分組).filter(Boolean));return ['全部',...GROUP_ORDER.filter(name=>available.has(name)),...Array.from(available).filter(name=>!GROUP_ORDER.includes(name)).sort((a,b)=>String(a).localeCompare(String(b),'zh-Hant'))];},[data]);const moonPhase=useMemo(()=>realMoonPhase(),[]);const graph=useMemo(()=>data?buildRuneGraph(data.runes,derivedFromEvolution(data.evolution),{writing:data.writing,relationships:data.relationships,eras:data.eras}):null,[data]);const rawGraphView=useMemo(()=>graph?searchRuneGraph(graph,graphQuery,graphGroup):{nodes:[],edges:[]},[graph,graphQuery,graphGroup]);const edgeTypes=useMemo(()=>[...new Set((graph?.edges||[]).map(edge=>edge.type))].sort(),[graph]);const graphView=useMemo(()=>{if(!graphEdge)return rawGraphView;const edges=rawGraphView.edges.filter(edge=>edge.type===graphEdge);const ids=new Set(edges.flatMap(edge=>[edge.source,edge.target]));return {nodes:rawGraphView.nodes.filter(node=>ids.has(node.id)),edges};},[rawGraphView,graphEdge]);
  useEffect(()=>{setNodePage(1);setEdgePage(1);},[graphQuery,graphGroup,graphEdge]);
  function chooseMode(key){timers.current.forEach(clearTimeout);setRitualStep(-1);setError('');setModeKey(key);setDraw(null);if(typeof window!=='undefined'){const url=new URL(window.location.href);url.searchParams.set('mode',key);window.history.replaceState({},'',`${url.pathname}${url.search}#draw`);}}
  function finishDraw(){try{if(!data?.runes?.length)throw new Error('符文資料尚未載入完成。');if(data.runes.length<selectedMode.count)throw new Error(`可抽取符文不足 ${selectedMode.count} 張。`);const cards=sampleUnique(data.runes,selectedMode.count),directionIndexes=cards.map(()=>randomInt(4)),directions=directionIndexes.map(index=>DIRECTIONS[index]),evaluation=evaluateSpread(cards,directions);setDraw({cards,directionIndexes,directions,evaluation});setError('');}catch(err){setDraw(null);setError(`抽牌失敗：${err?.message||'未知錯誤'}`);}finally{setRitualStep(-1);}}
  function executeDraw(){if(!data||ritualStep>=0)return;setError('');setDraw(null);timers.current.forEach(clearTimeout);timers.current=[];setRitualStep(0);[1,2,3,4].forEach(step=>timers.current.push(setTimeout(()=>setRitualStep(step),step*1000)));timers.current.push(setTimeout(finishDraw,5000));}
  const ritualMessages=RITUAL_MESSAGES[modeKey]||RITUAL_MESSAGES.single;const nodePages=Math.max(1,Math.ceil(graphView.nodes.length/PAGE_SIZE)),edgePages=Math.max(1,Math.ceil(graphView.edges.length/PAGE_SIZE));const shownNodes=graphView.nodes.slice((nodePage-1)*PAGE_SIZE,nodePage*PAGE_SIZE),shownEdges=graphView.edges.slice((edgePage-1)*PAGE_SIZE,edgePage*PAGE_SIZE);const liveGuidance=draw?finalGuidance(data?.lots,draw.cards.at(-1),draw.directions.at(-1)):'';

  return <>
    <header className="loc-next-header"><div className="loc-next-nav-stack"><nav className="loc-next-nav loc-next-nav-primary" aria-label="LOC 主要導覽"><a href="/runes" aria-current="page">月之符文</a><a href="/context">脈絡</a><a href="/statics">統計</a><a href="/evolution">推演</a><a href="/my-style">設定</a><form className="loc-next-search" action="/search" method="get" role="search"><input name="q" type="search" aria-label="搜尋文字" placeholder="輸入文字"/><button type="submit">搜尋</button></form><a className="loc-next-home" href="/">回月典首頁</a></nav></div></header>
    <nav className="runes-subnav" aria-label="月之符文功能導覽"><a href="#intro">新手上路</a><a href="#draw">占卜抽籤</a><a href="/game">遊戲</a><a href="#library">符文圖鑑</a><a href="#reference">符文脈絡</a><a href="/statics">符文統計</a><a href="#reference">符文知識庫</a></nav>
    <main className="loc-next-main"><section className="loc-view">
      <header className="loc-hero" id="intro"><p className="loc-eyebrow">LunaRunes · 月之符文</p><h1>月之符文</h1><p>由 66 個中文單一字構成。可以問一件事，也可以沒有問題直接抽取；抽牌、加權與籤詩指引都在瀏覽器本機完成，不需要外部 API。</p></header>
      <section className="loc-card" id="draw" data-draw-keyword="lunarunes-draw" data-draw-mode={modeKey}><p className="loc-eyebrow">Draw · 抽籤</p><h2>選擇抽牌方式</h2><div className="runes-mode-nav">{MODES.map(item=><button key={item.key} data-draw-mode={item.key} className={`loc-button ${modeKey===item.key?'primary':''}`} onClick={()=>chooseMode(item.key)}>{item.label}</button>)}</div><div className="loc-actions runes-draw-action"><button className="loc-button primary" data-draw-action="execute" onClick={executeDraw} disabled={!data||ritualStep>=0}>{ritualStep>=0?'占卜中…':'抽牌'}</button></div><p className={`loc-status ${error?'error':''}`}>{error||(!data?'載入月之符文資料中…':`${selectedMode.label}：${selectedMode.positions.join(' → ')}${modeKey==='daily'?`／真實月相：${moonPhase}`:''}`)}</p></section>
      {ritualStep>=0&&<section className="loc-card runes-ritual" data-draw-stage="ritual" data-draw-mode={modeKey} aria-live="polite"><div className="runes-ritual-card"><img src="/assets/lunarunes/cards/65_玄.png" alt="玄之符文"/><strong>玄之符文</strong><span>Chaos</span></div><div className="runes-ritual-copy"><p className="loc-eyebrow">等待片刻</p><h2>{ritualMessages[ritualStep]}</h2><p>真實月相：{moonPhase}</p></div></section>}
      {draw&&<>
        <section className="loc-card" id="result" data-draw-stage="result" data-draw-mode={modeKey}><div className="loc-result-meta"><span>{selectedMode.label}</span><span>真實月相：{moonPhase}</span></div><div className="loc-draw-grid">{draw.cards.map((card,index)=><article className="loc-context-item compact loc-draw-card" data-rune-id={card.編號} data-draw-position={selectedMode.positions[index]||index+1} key={`${card.編號}-${index}`}><small>{selectedMode.positions[index]||`第 ${index+1} 張`}</small><img className={`loc-rune-card-image ${ROTATION_CLASSES[draw.directionIndexes[index]]}`} src={runeCardImage(card)} alt={`${card.符文名稱}符文卡`}/><b>{card.符文名稱}</b><span>{draw.directions[index]} · {card.卡片屬性||'中平'}</span><small>{directionText(card,draw.directions[index])||card.符文說明}</small><div className="runes-draw-keywords"><span><strong>正向關鍵詞</strong>{card.正向關鍵詞||'—'}</span><span><strong>反向關鍵詞</strong>{card.反向關鍵詞||'—'}</span></div></article>)}</div><div className="loc-actions runes-retry"><button className="loc-button" data-draw-action="retry" onClick={executeDraw}>再抽一次</button></div></section>
        {modeKey==='single'&&<section className="loc-card" data-draw-reading="single"><p className="loc-eyebrow">Reading · 單卡解讀</p><h2>{draw.cards[0].符文名稱} · {draw.directions[0]}</h2><SingleAdvice card={draw.cards[0]} direction={draw.directions[0]} phase={moonPhase}/></section>}
        {modeKey==='daily'&&<section className="loc-card" data-draw-reading="daily"><p className="loc-eyebrow">Daily · 每日指示</p><h2>{draw.cards[0].符文名稱} · {draw.directions[0]} · {moonPhase}</h2><SingleAdvice card={draw.cards[0]} direction={draw.directions[0]} phase={moonPhase} daily/></section>}
        <MultiReading draw={draw} mode={modeKey} phase={moonPhase}/>
        {modeKey==='ow3gs'&&<section className="loc-card runes-ow3gs-core" data-draw-reading="ow3gs"><p className="loc-eyebrow">OW3gs · 核心判定</p><h2>第 7–11 張為核心判定</h2><div className="loc-context-list">{draw.cards.slice(6,11).map((card,index)=><div className="loc-context-item" key={`core-${card.編號}-${index}`}><strong>第 {index+7} 張 · {card.符文名稱} · {draw.directions[index+6]}</strong><span>{directionText(card,draw.directions[index+6])||card.符文說明}</span></div>)}</div><p>整體指示分數：{draw.evaluation.score.toFixed(3)} · 整體趨勢：{draw.evaluation.range.label}</p></section>}
        <section className="loc-card" data-draw-stage="guidance"><p className="loc-eyebrow">Semantic Guidance · 語意指示</p><h2>整體趨勢：{draw.evaluation.range.label}</h2><p>指示分數：{draw.evaluation.score.toFixed(3)}。依符文詞性、卡片位向與牌位權重計算目前組合的整體語意傾向；分數不代表吉凶、好壞或結果機率。{modeKey==='ow3gs'?'第 7–11 張採核心權重。':''}</p><div className="loc-table-wrap"><table className="loc-table"><thead><tr><th>位置</th><th>符文</th><th>詞性</th><th>位向</th><th>權重</th><th>加權值</th></tr></thead><tbody>{draw.evaluation.rows.map((row,index)=><tr key={`${row.card.編號}-${index}`}><td>{selectedMode.positions[index]||index+1}</td><td>{row.card.符文名稱}</td><td>{row.card.卡片屬性||'中平'}</td><td>{row.direction}</td><td>{row.weight}</td><td>{row.weighted.toFixed(2)}</td></tr>)}</tbody></table></div></section>
        <section className="loc-card" data-draw-stage="lots"><p className="loc-eyebrow">Lots · 籤詩</p><h2>籤詩指引</h2><p>沿用最後一張「{draw.cards.at(-1)?.符文名稱} · {draw.directions.at(-1)}」的既有籤詩指示。</p><div className="loc-context-list">{data?.lots?.length?splitDomainGuidance(liveGuidance).map((line,index)=><div className="loc-context-item" key={`${line}-${index}`}>{line}</div>):<div className="loc-context-item">籤詩資料仍在本機載入；抽牌與關鍵詞判定不受影響。</div>}</div></section>
      </>}
      <RuneAtlas runes={data?.runes||[]} groups={groups} group={group} setGroup={setGroup}/>
      <section className="loc-card" id="reference"><p className="loc-eyebrow">Reference · 符文脈絡與知識庫</p><h2>月之符文 Graph</h2><p>以現行符文、正反向關鍵詞、群組與演化紀錄建立本機關係圖，並由已治理名冊補入作品、角色、歌曲、ERA 與跨媒介關係；名冊只補結構，不反向改寫符文判定。</p><form className="runes-graph-controls" onSubmit={event=>event.preventDefault()}><input value={graphQuery} onChange={event=>setGraphQuery(event.target.value)} type="search" placeholder="搜尋符文、關鍵詞或定義"/><select value={graphGroup} onChange={event=>setGraphGroup(event.target.value)}><option value="">全部群組</option>{groups.filter(name=>name!=='全部').map(name=><option key={name}>{name}</option>)}</select><select value={graphEdge} onChange={event=>setGraphEdge(event.target.value)}><option value="">全部關係</option>{edgeTypes.map(type=><option key={type}>{type}</option>)}</select><button type="button" className="loc-button" onClick={()=>{setGraphQuery('');setGraphGroup('');setGraphEdge('')}}>清除</button></form><p className="loc-status">本機 Graph · {graphView.nodes.length} 個節點 / {graphView.edges.length} 條關係</p><div className="runes-graph-columns"><div><h3>節點</h3><div className="loc-context-list">{shownNodes.map(node=><button type="button" className="loc-context-item runes-graph-node" key={node.id} onClick={()=>setGraphQuery(node.label)}><small>{node.type} · {node.group||node.period||node.source_type||''}</small><strong>{node.label}</strong><span>{node.definition||node.english||''}</span></button>)}</div><div className="runes-pager"><button disabled={nodePage<=1} onClick={()=>setNodePage(page=>page-1)}>上一頁</button><span>{nodePage} / {nodePages}</span><button disabled={nodePage>=nodePages} onClick={()=>setNodePage(page=>page+1)}>下一頁</button></div></div><div><h3>關係</h3><div className="loc-context-list">{shownEdges.map((edge,index)=><div className="loc-context-item" key={`${edge.source}-${edge.type}-${edge.target}-${index}`}><small>{edge.source_type||'—'}{edge.registry?` · ${edge.registry}`:''}</small><strong>{edge.type}</strong><span>{edge.source} → {edge.target}</span></div>)}</div><div className="runes-pager"><button disabled={edgePage<=1} onClick={()=>setEdgePage(page=>page-1)}>上一頁</button><span>{edgePage} / {edgePages}</span><button disabled={edgePage>=edgePages} onClick={()=>setEdgePage(page=>page+1)}>下一頁</button></div></div></div><div className="runes-reference-grid"><figure><img src="/assets/lunarunes/reference/loc_runes_66_overview.jpg" alt="月之符文66總覽" loading="lazy"/><figcaption>月之符文66總覽</figcaption></figure><figure><img src="/assets/lunarunes/reference/LunaRunes64_S.png" alt="月之符文參考圖" loading="lazy"/><figcaption>月之符文參考圖</figcaption></figure></div></section>
    </section></main>
  </>;
}
