name = "loc-state"
main = "loc-state-worker.js"
compatibility_date = "2026-09-12"

routes = [
  { pattern = "loc.lo3rwang.cc/api/loc-state/*", zone_name = "lo3rwang.cc" }
]

[[kv_namespaces]]
binding = "LOC_KV"
id = "69132df38f8f43a6a40cae39ebfe5460"

[vars]
PUBLIC_ORIGIN = "https://loc.lo3rwang.cc"