'use client';
import {useEffect,useMemo,useState} from 'react';
import {fetchLocJson,LOC_DATA} from '../data';
import {useLocalStore} from '../local-store';
import RuneSemanticAnalyzer from '../components/RuneSemanticAnalyzer';
const TABS=[['overview','總覽'],['semantic','符文判定'],['events','事件'],['relations','關係式'],['scenarios','情境 Scenario']];const UI_SETTINGS_KEY='loc-ui-settings-v1';const DEFAULT_UI_SETTINGS={draw_response:'ritual',list_page_size:10};const LIST_PAGE_OPTIONS=[5,10,15,20,25,50];
function Pagination({page,total,pageSize,onChange}){const pages=Math.max(1,Math.ceil(total/pageSize));if(total<=pageSize)return null;return <div className="loc-pagination"><span>第 {page} / {pages} 頁 · 共 {total} 筆 · 每頁 {pageSize}</span><div><button className="loc-button" disabled={page<=1} onClick={()=>onChange(page-1)}>上一頁</button><button className="loc-button" disabled={page>=pages} onClick={()=>onChange(page+1)}>下一頁</button></div></div>}
export default function ContextView(){const {value:uiSettings}=useLocalStore(UI_SETTINGS_KEY,DEFAULT_UI_SETTINGS);const [tab,setTab]=useState('overview');const [events,setEvents]=useState(null),[relations,setRelations]=useState(null),[scenarios,setScenarios]=useState(null);const [error,setError]=useState('');const [eventPage,setEventPage]=useState(1),[relationPage,setRelationPage]=useState(1),[scenarioPage,setScenarioPage]=useState(1),[scenarioGroup,setScenarioGroup]=useState(''),[scenarioQuery,setScenarioQuery]=useState('');const pageSize=LIST_PAGE_OPTIONS.includes(Number(uiSettings?.list_page_size))?Number(uiSettings.list_page_size):10;
useEffect(()=>{let live=true;const load=(path,setter)=>fetchLocJson(path).then(data=>live&&setter(data)).catch(e=>live&&setError(e.message));setError('');if(tab==='events'&&!events)load(LOC_DATA.LOC8_EVENT_SNAPSHOT,setEvents);if(tab==='relations'&&!relations)load(LOC_DATA.LOC_CROSS_RELATIONSHIP_REGISTRY,setRelations);if(tab==='scenarios'&&!scenarios)load(LOC_DATA.LOC2_EVENT_REGISTRY,setScenarios);return()=>{live=false}},[tab,events,relations,scenarios]);useEffect(()=>{setEventPage(1);setRelationPage(1);setScenarioPage(1)},[pageSize]);
const eventRows=useMemo(()=>[...(events?.events||[])].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))),[events]);const relationRows=relations?.relationships||[];const scenarioRows=scenarios?.records||[];const groups=useMemo(()=>[...new Set(scenarioRows.map(x=>x.event_group).filter(Boolean))],[scenarioRows]);const filteredScenarios=useMemo(()=>{const query=scenarioQuery.trim().toLocaleLowerCase('zh-Hant');return scenarioRows.filter(item=>(!scenarioGroup||item.event_group===scenarioGroup)&&(!query||[item.event_id,item.title,item.event_group,item.requirement_signature,item.description].join(' ').toLocaleLowerCase('zh-Hant').includes(query)))},[scenarioRows,scenarioGroup,scenarioQuery]);const shownEvents=eventRows.slice((eventPage-1)*pageSize,eventPage*pageSize),shownRelations=relationRows.slice((relationPage-1)*pageSize,relationPage*pageSize),shownScenarios=filteredScenarios.slice((scenarioPage-1)*pageSize,scenarioPage*pageSize);
return <section className="loc-view"><header className="loc-hero"><p className="loc-eyebrow">Context · 脈絡</p><h1>脈絡</h1><p>事件、關係、情境與語意判定的統一入口。Rune Algorithm 的結果與理由在此可直接檢視；資料按功能載入。</p></header><nav className="loc-tabs" aria-label="脈絡功能">{TABS.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>{error&&<div className="loc-status error">{error}</div>}
{tab==='overview'&&<div className="loc-grid two"><section className="loc-card"><p className="loc-eyebrow">Context Flow</p><h2>從文字到理由</h2><p>文字先由分類模組建立語意結果；Context 負責展示事件、關係與「為什麼被判成這些符文」，不另外發明第二套分類。</p></section><section className="loc-card"><p className="loc-eyebrow">Graph Governance</p><h2>關係來自脈絡證據</h2><p>不再以 runes.json 關鍵詞重疊自動製造 Rune ↔ Rune Edge。關係應由實際文本、事件或已治理的關係資料形成。</p></section></div>}
{tab==='semantic'&&<RuneSemanticAnalyzer/>}
{tab==='events'&&<section className="loc-card"><p className="loc-eyebrow">Context / Event</p><h2>事件</h2>{!events?<p>載入事件…</p>:<><div className="loc-context-list">{shownEvents.map(item=><article className="loc-context-item" key={item.id}><div className="loc-result-meta"><time>{item.date}</time><span>{item.event_type||item.status}</span></div><h3>{item.title}</h3><p>{item.description}</p>{item.state_after&&<p><strong>狀態 State →</strong> {item.state_after}</p>}</article>)}</div><Pagination page={eventPage} total={eventRows.length} pageSize={pageSize} onChange={setEventPage}/></>}</section>}
{tab==='relations'&&<section className="loc-card"><p className="loc-eyebrow">Context / Relation</p><h2>關係式</h2>{!relations?<p>載入關係…</p>:<><div className="loc-context-list">{shownRelations.map(item=><article className="loc-context-item" key={item.relationship_id}><div className="loc-result-meta"><span>類型 Type：{item.relation_type}</span><span>證據 Evidence：{item.evidence_status}</span></div><h3>{item.source?.title||item.canonical_key}</h3><p>{item.relation_summary}</p><div className="loc-chip-list">{item.targets?.map(target=><span key={`${item.relationship_id}-${target.work_ref}`}>→ {target.title||target.work_ref}</span>)}</div></article>)}</div><Pagination page={relationPage} total={relationRows.length} pageSize={pageSize} onChange={setRelationPage}/></>}</section>}
{tab==='scenarios'&&<section className="loc-card"><p className="loc-eyebrow">Context / Scenario</p><h2>情境語料庫 Scenario Corpus</h2>{!scenarios?<p>載入情境 Scenario…</p>:<><div className="loc-filter-row"><select value={scenarioGroup} onChange={e=>{setScenarioGroup(e.target.value);setScenarioPage(1)}}><option value="">全部群組</option>{groups.map(group=><option key={group} value={group}>{group}</option>)}</select><input value={scenarioQuery} onChange={e=>{setScenarioQuery(e.target.value);setScenarioPage(1)}} placeholder="搜尋情境"/></div><div className="loc-context-list">{shownScenarios.map(item=><article className="loc-context-item" key={item.event_id}><div className="loc-result-meta"><span>群組 Group：{item.event_group}</span><span>需求簽章 Signature：{item.requirement_signature}</span></div><h3>{item.event_id} · {item.title}</h3><p>{item.description}</p></article>)}</div><Pagination page={scenarioPage} total={filteredScenarios.length} pageSize={pageSize} onChange={setScenarioPage}/></>}</section>}</section>}
