export default function GovernanceView(){
  return <section className="loc-view">
    <header className="loc-hero" id="top"><p className="loc-eyebrow">Governance</p><h1>治理</h1><p className="loc-subtitle">用可解釋的原則治理分類，而不是累積例外字典</p><p>LOC 治理要求分類方法說得清楚、可以重複使用，也可以在規則更新後重新分析原始資料。月之符文是 LOC 的參照實作：它展示如何以少量基本語意原則完成簡單分類，而不是要求其他語言或文化採用相同符文答案。</p></header>
    <div className="loc-grid two">
      <section className="loc-card" id="principles"><p className="loc-eyebrow">LOC Governance</p><h2>治理方法</h2><p className="loc-core-line">基本語意 → 完整詞義 → 判別原則 → 可解釋結果</p><p><strong>關鍵字只是候選。</strong>字面命中不能直接當成分類結果；系統必須確認完整詞／詞組中，符文的實際語意是否成立。</p><p><strong>從例外找原則。</strong>新案例先由既有原則處理；反覆出現的語意行為再整理成通則，不把每一筆加入例外表。</p><p><strong>例外最小化。</strong>只有無法由通則推出、且具有穩定完整義或明確 Scope 的內容才保留。</p><p><strong>不計算數值語意權重。</strong>允許零枚、一枚或多枚符文成立，不強迫唯一主符文。</p></section>
      <section className="loc-card" id="rune-algorithm"><p className="loc-eyebrow">Rune Algorithm</p><h2>四種基本判別</h2><p><strong>AND｜並存：</strong>時空 → 時 + 空；風向 → 風 + 向；明火 → 明 + 火。</p><p><strong>PLUS｜增義：</strong>原義仍成立，再增加語意維度。天時 → 時 + 緣。</p><p><strong>OVERRIDE｜完整義：</strong>完整詞形成穩定義，優先於拆字。時辰 → 辰；清明 → 辰；日月當空 → 明。</p><p><strong>DEFER｜延後判別：</strong>特殊 Canon 字面先等待完整語意。日蝕 → 日；月蝕 → 月；日期 → 時；日月作歲月／時期 → 辰。</p></section>
      <section className="loc-card" id="classification"><p className="loc-eyebrow">Classification Flow</p><h2>實際分類流程</h2><p className="loc-core-line">文字 → 完整詞／詞組 → 候選證據 → AND / PLUS / OVERRIDE / DEFER → 符文歸屬</p><p>詞性與句內語意角色只協助消歧；群組與基本定義提供語意邊界。上下文不足就保留 disputed，不以虛構分數製造假精確。</p><p>Context 顯示判定結果與理由；Statistics 只統計演算法確認的 semantic hits，不把中文字面出現次數當符文統計。</p></section>
      <section className="loc-card" id="semantic-boundaries"><p className="loc-eyebrow">Semantic Boundaries</p><h2>語意邊界</h2><p><strong>時：</strong>時間本身、時間規則、尺度與期間計量。</p><p><strong>辰（Phase）：</strong>時期、階段與節氣。</p><p><strong>緣（Karma）：</strong>時間與事件、條件、對象交互形成的適合時機；不是宿命式有緣／沒緣。</p><p><strong>誤（Error）：</strong>資訊、理解或判斷本身的錯誤；延誤不因含「誤」字就歸誤。</p><p><strong>日／月：</strong>日固定為日蝕，月固定為月蝕／月蝕陰暗面；一般字面採 DEFER。</p><p><strong>固定邊界：</strong>水 = Water；流動核心歸氣；氣 = Air；暗 = Shadow；空 = Space；無 = Blank；虛 = Void；玄 = Chaos。</p></section>
      <section className="loc-card" id="author-governance"><p className="loc-eyebrow">Author Governance</p><h2>德之符文</h2><p>德（0）保留但不屬 66 符抽取池；它是作者治理指派，不是看到「德」字就自動分類。</p><p>現行保留詞：<strong>微月光、人生月台、斜教、OW3gs</strong> → 德。只有 Author Scope 成立才套用。</p></section>
      <section className="loc-card" id="culture-positioning"><p className="loc-eyebrow">Culture Scope</p><h2>文化與分類主體</h2><p>LunaRunes 可以依自己的 Canon 對文字做 LunaRunes projection，但不是對來源文化的正誤判決。其他語言、文化、作者或符號系統可以建立自己的基本語意、組合原則與特殊治理。</p><p>對自身作品的治理權，不延伸為對其他人的思想、文化或獨立符文體系的治理權。</p></section>
      <section className="loc-card" id="era"><p className="loc-eyebrow">Rune ERA & Culture</p><h2>符文時期與歷史觀察</h2><p>Rune ERA 正式節點為 <strong>14 → 24 → 32 → 42 → 66</strong>；40 與 64 保留為 RC／轉換歷史，不另立正式 ERA。</p><p>Culture 觀察形成、延續、轉變、分化、消退、回返與擺盪，只描述歷史資料，不預測未來。</p><p className="loc-core-line">Corpus → Rune Algorithm → Semantic Hits → ERA → Statistics → Culture</p></section>
      <section className="loc-card" id="neutrality"><p className="loc-eyebrow">Neutrality</p><h2>中立與個人決定權</h2><p>LOC／LunaRunes 整理可觀察資料、語意、關係與歷史差異，不把分類結果變成使用者必須接受的價值結論。內容描述與價值判斷分開治理；最後選擇仍由使用者決定。</p></section>
      <section className="loc-card" id="copyleft"><p className="loc-eyebrow">Copyleft & Audit</p><h2>開放參考與衍生治理</h2><p>任何人都可以學習、參考並建立自己的符文或符號式語言。當作品實質沿用 LunaRunes 具有辨識性的內容、資料或整體特質時，應尊重並揭示來源。</p><p><strong>Attribution ≠ Endorsement。</strong>標示原作者或 Audit 不代表原作者推薦、認可或背書；背書必須另有明確授權。</p></section>
    </div>
  </section>
}
