#!/usr/bin/env python3
"""Build the browser-facing Search source statistics JS snapshot.

The generated JSON remains the batch/statistics exchange format. Search and
Statics load this tiny JS projection at runtime so they do not need to fetch
or parse the full generated JSON file.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data/json/generated/search/SEARCH_SOURCE_STATS.json"
TARGET = ROOT / "js/search-source-stats.js"


def slim_source(row: dict) -> dict:
    keys = (
        "source", "records", "searchable_records", "fulltext_records",
        "public_url_records", "start_date", "end_date", "status",
        "char_count", "source_type", "source_category", "content_counts",
        "char_count_applicable",
    )
    return {key: row[key] for key in keys if key in row}


def build(data: dict) -> dict:
    search_summary = data.get("search_summary") or {}
    text_summary = data.get("text_summary") or {}
    knowledge = data.get("knowledge_summary") or {}
    return {
        "schema_version": data.get("schema_version", "1.0"),
        "generated_at": data.get("generated_at", ""),
        "search_summary": {
            key: search_summary[key]
            for key in ("comparable_records", "comparable_scope", "char_count", "char_count_scope", "char_count_breakdown")
            if key in search_summary
        },
        "text_summary": {
            key: text_summary[key]
            for key in ("catalogued_records", "searchable_records", "fulltext_records", "start_date", "end_date", "char_count", "char_count_unit")
            if key in text_summary
        },
        "text_sources": [slim_source(row) for row in data.get("text_sources", [])],
        "media_sources": [slim_source(row) for row in data.get("media_sources", [])],
        "knowledge_summary": {
            key: knowledge[key]
            for key in ("registered_assets", "faq_items", "searchable_unit_floor", "knowledge_document_records", "knowledge_document_characters")
            if key in knowledge
        },
    }


def main() -> None:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    payload = json.dumps(build(data), ensure_ascii=False, separators=(",", ":"))
    TARGET.write_text(
        "// Generated by tools/build_search_source_stats_js.py; do not edit by hand.\n"
        f"window.LOC_SEARCH_SOURCE_STATS=Object.freeze({payload});\n",
        encoding="utf-8",
    )
    print(TARGET.relative_to(ROOT))


if __name__ == "__main__":
    main()
