export const LOC_DATA=Object.freeze({
  RUNES:'canonical/runes',
  LOTS:'canonical/lots',
  HISTORY:'canonical/history',
  HARMONY:'canonical/harmony',
  RUNE_GRAMMAR:'canonical/rune-grammar',
  RUNE_INTERPRETATIONS:'canonical/rune-interpretations',
  THREE_CARD_COMBINATIONS:'canonical/three-card-combinations',

  LOC2_EVENT_REGISTRY:'context/loc2-events',
  LOC3_PERIOD_KEYWORD_ANALYSIS:'culture/loc3-period-keywords',
  LOC4_WRITING_REGISTRY:'literary/loc4-writing',
  LOC6_GOVERNANCE_REGISTRY:'governance/loc6',
  PERIOD_KEYWORD_ANALYSIS:'culture/period-keywords',
  LOC6_PERIOD_KEYWORD_ANALYSIS:'culture/loc6-period-keywords',
  DAILY_RUNE_REPO_HISTORY:'evolution/daily-rune-history',
  LOC8_DAILY_RUNE_REPO_HISTORY:'evolution/daily-rune-history',
  LOC8_EVENT_SNAPSHOT:'context/loc8-events',
  LOC_CROSS_RELATIONSHIP_REGISTRY:'context/cross-relations',
  LO3RWANG_ERA:'culture/lo3rwang-periods',
  LOC_GRAPH_SCHEMA:'context/graph-schema',
  LOC_STYLE_GROUP_REGISTRY:'governance/style-groups',
  LOC_KNOWLEDGE_ASSET_REGISTRY:'knowledge/assets',
  LOC_SEARCH_GOVERNANCE:'knowledge/search-governance',
  LRUNES_ERA:'culture/lrunes-periods',
  ZHENGDE_CULTURE_KEYWORDS:'culture/zhengde-keywords',

  LOC_FAQ:'knowledge/faq',
  RUNE_RESERVED_SNAPSHOT:'canonical/runes',
  SEARCH_SOURCE_STATS:'knowledge/search-stats'
});
